/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DocsSplatRouteImport } from "./routes/docs/$";
import { Route as PricingPageRouteImport } from "./routes/pricing/page";
import { Route as ApiSearchPageRouteImport } from "./routes/api/search/page";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: "/docs/$",
  path: "/docs/$",
  getParentRoute: () => rootRouteImport,
} as any);
const PricingPageRoute = PricingPageRouteImport.update({
  id: "/pricing/",
  path: "/pricing/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSearchPageRoute = ApiSearchPageRouteImport.update({
  id: "/api/search/",
  path: "/api/search/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/pricing/": typeof PricingPageRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/api/search/": typeof ApiSearchPageRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/pricing": typeof PricingPageRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/api/search": typeof ApiSearchPageRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/pricing/": typeof PricingPageRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/api/search/": typeof ApiSearchPageRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/pricing/" | "/docs/$" | "/api/search/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/pricing" | "/docs/$" | "/api/search";
  id: "__root__" | "/" | "/pricing/" | "/docs/$" | "/api/search/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  PricingPageRoute: typeof PricingPageRoute;
  DocsSplatRoute: typeof DocsSplatRoute;
  ApiSearchPageRoute: typeof ApiSearchPageRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/$": {
      id: "/docs/$";
      path: "/docs/$";
      fullPath: "/docs/$";
      preLoaderRoute: typeof DocsSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pricing/": {
      id: "/pricing/";
      path: "/pricing";
      fullPath: "/pricing/";
      preLoaderRoute: typeof PricingPageRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/search/": {
      id: "/api/search/";
      path: "/api/search";
      fullPath: "/api/search/";
      preLoaderRoute: typeof ApiSearchPageRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PricingPageRoute: PricingPageRoute,
  DocsSplatRoute: DocsSplatRoute,
  ApiSearchPageRoute: ApiSearchPageRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
